apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: param-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdapp-param-demo  
    server: 'https://kubernetes.default.svc'
  source:
    path: params_demo
    repoURL: 'https://github.com/glsanthosh/argocd-example-apps.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
