apiVersion: v1
kind: Pod
metadata:
  name: sandemo-pod
  namespace: sandemo-pod
  annotations:
    argocd.argoproj.io/sync-options: Validate=true
spec:
  invalidField: invalidValueof # This field is intentionally invalid
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
  # Intentional Schema Validation Issue
  # The 'replicas' field is not valid for a Pod specification.
  invalidField: invalidValue  # This field is intentionally invalid
