apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-response-time-check
spec:
  metrics:
  - name: response-time
    provider:
      prometheus:
        address: http://prometheus-operated.default.svc.cluster.local  # Update based on your Prometheus setup
        query: |
          histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app="simple-http-server"}[5m])) by (le))
    successCondition: "result <= 0.3"
    failureCondition: "result > 0.3"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: http-server
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-server
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: simple-http-server


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-http-server-monitor
spec:
  selector:
    matchLabels:
      app: simple-http-server
  endpoints:
  - port: http
    interval: 15s


apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-http-server-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: http-server
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 15s}
      - analysis:
          templates:
          - templateName: http-response-time-check
      - setWeight: 100
