apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prunetestapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdappdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: Nginx_Deployment_Prune
    repoURL: 'https://github.com/glsanthosh/argocd-example-apps.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
